# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement # Corvax-RoleTime
      role: JobChemist
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 30000
  weight: 10
  startingGear: CMOGear
  icon: "ChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  minBankBalance: 800
  maxBankBalance: 1200
  wageDepartment: Command
  wage: 200

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    id: CMOPDA
    ears: ClothingHeadsetAltMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelCMOFilled
  duffelbag: ClothingBackpackDuffelCMOFilled
