- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 30000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 30000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 30000
    - !type:OverallPlaytimeRequirement
      time: 180000
  weight: 20
  startingGear: CaptainGear
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  minBankBalance: 800
  maxBankBalance: 1200
  wageDepartment: Command
  wage: 200

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
