- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5400
  startingGear: SecurityOfficerGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Security
  wage: 100

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    #head: ClothingHeadHelmetHelmet # Corvax-Resprite
    #outerClothing: ClothingOuterVestKevlar
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    #belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
