- type: job
  id: Warden
  name: job-name-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 12000
  startingGear: WardenGear
  icon: "Warden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Armory
  - Maintenance
  - Service
  - Brig
  - External
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Security
  wage: 100

- type: startingGear
  id: WardenGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    #outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    #belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
