- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  accountNumber: 1315

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  roles:
  - Bartender
  - Botanist
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Maid
  - MedicalIntern
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Zookeeper
  - SecurityCadet
  - ServiceWorker
  - TechnicalAssistant
  accountNumber: 1316

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - CentralCommandOfficial
  - IAA
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - Adjutant
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  accountNumber: 1317

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  accountNumber: 1318

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  accountNumber: 1319

- type: department
  id: Security
  description: department-Command-description
  color: "#DE3A3A"
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  accountNumber: 1320

- type: department
  id: Science
  description: department-Command-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  accountNumber: 1321
