- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "Psychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Medical
  wage: 100

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  innerclothingskirt: ClothingUniformJumpskirtPsychologist # Corvax-Resprite
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
