- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # Corvax-RoleTime
  startingGear: ChefGear
  icon: "Chef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Civilian
  wage: 100

- type: startingGear
  id: ChefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    head: ClothingHeadHatChef
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronChef
  innerclothingskirt: ClothingUniformJumpskirtChef
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
