- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 30000
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  minBankBalance: 800
  maxBankBalance: 1200
  wageDepartment: Command
  wage: 200

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLab
    id: RnDPDA
    ears: ClothingHeadsetRD
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
