- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  startingGear: ScientistGear
  icon: "Scientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Science
  wage: 100

- type: startingGear
  id: ScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
